### ISSUE TITLE
你好，请问content组件内的元素样式能自定义吗？

### ISSUE THREAD

**Issue by vanoneang** [Yubisaki/vuepress-theme-yubisaki#11]
我看到content组件是直接Vue.component('Content', Content)注册到了vue实例上，而具体content组件的实现content.js里面看不太懂，这样content里面解析md的格式就是固定的了

1.请问content组件的具体实现在那个位置？

2.content组件内的元素样式是否可以自定义？

谢谢

**Comment by Bloss** [comment]
1. content 组件是 vuepress 全局注册的
2. 自己找出 content 中的元素样式进行覆盖就可以了

**Comment by vanoneang** [comment]
嗯嗯，谢谢，我刚试了下，直接修改样式就可以进行更改了，谢谢

**Comment by xiaoxinshiwo** [comment]
> 嗯嗯，谢谢，我刚试了下，直接修改样式就可以进行更改了，谢谢

你好，我也想修改content的样式，请问怎么做呢？

**Comment by Bloss** [comment]
@xiaoxinshiwo 可以参考 vuepress 文档 https://vuepress.vuejs.org/zh/guide/markdown-slot.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E9%9C%80%E8%A6%81-markdown-%E6%8F%92%E6%A7%BD
