### ISSUE TITLE
gitalk配置问题

### ISSUE THREAD

**Issue by ZjBlog** [Yubisaki/vuepress-theme-yubisaki#15]
gitalk配置中id:location.pathname
我运行不起来，location不存在  如何解决?
FAIL  ReferenceError: location is not defined
 at Object.<anonymous> (F:\zjblog\docs\.vuepress\config.js:44:9)

**Comment by Bloss** [comment]
sorry，可以尝试不配置 id 字段。

**Comment by ZjBlog** [comment]
@Bloss  配置成功之后，使用github账号登录成功后，页面显示的还是登录之前的样式，没有改变，还是让我登录，如果我刷新页面，样式会发生改变，但是issue会有两条一模一样的数据？请问你配置的时候有这个问题吗？

**Comment by Bloss** [comment]
没有碰到过，可以提供你放置评论的 repo 看一下吗，登录成功之后，是会在 `localStorage` 中放置 accessToken 的，之后再次登录使用该 token 登录，所以你可以看一下 `localStorage` 中是否有 `GT_ACCESS_TOKEN ` 数据项。

**Comment by ZjBlog** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/15625370/45990488-1ba0c480-c0b3-11e8-9d6f-28a991719dad.jpg)
地址 https://github.com/ZjBlog/comment/issues
谢谢

**Comment by Bloss** [comment]
代码层面来看，没有发起两次请求，具体原因不是很好分析。
你可以尝试去 [gitalk](https://github.com/gitalk/gitalk) 发起 issue

**Comment by ZjBlog** [comment]
好的 ，谢谢

**Comment by xiaoxinshiwo** [comment]
如果id不配置显示：未找到相关的 Issues 进行评论
如果配置为 id: 'comment', 则在不同文档标题的评论都在一个issue上了

**Comment by xiaoxinshiwo** [comment]
> @xiaoxinshiwo
> 
> 默认的 id 是 `document.title`
我的配置：
```
 comment: {
      clientID: 'dcb2c98bdb97b6f5e37f',
      clientSecret: 'a58fc9ff4e53f1e26539fb621d65402d501027c4',
      repo: 'zhangyongxin',
      owner: 'xiaoxinshiwo',
      admin: ['xiaoxinshiwo'],
      perPage: 5,
      id: 'comment',      // Ensure uniqueness and length less than 50
      distractionFreeMode: false  // Facebook-like distraction free mode
    },
```
有问题吗？

**Comment by xiaoxinshiwo** [comment]
> @xiaoxinshiwo
> 
> 默认的 id 是 `document.title`
 
我现在没配置id了，但是会出现多个comment挤在一个issue里面，但是刷新后又好了，甚是费解
