### ISSUE TITLE
markdown-it was update

### ISSUE THREAD

**Issue by ErgoFriend** [Yubisaki/vuepress-theme-yubisaki#16]
cannot import markdown-it-task-lists and markdown-it-imsize

**Comment by Bloss** [comment]
do you run npm install them

**Comment by Bloss** [comment]
Which version of vuepress? Since @1.0.0.alpha.x, markdown config has been extend with plugins api, as a corresponding, the theme updated to @vuepress-theme-yubisaki@next version.
