### ISSUE TITLE
请问：使用<!-- more --> 标签出现了重复标题现象，怎么解决呢

### ISSUE THREAD

**Issue by xiaoxinshiwo** [Yubisaki/vuepress-theme-yubisaki#18]
使用 标签出现了重复标题现象；
现象：https://s1.ax1x.com/2018/11/08/i7dvMn.png

**Comment by Bloss** [comment]
可以提供能复现问题的 repo 吗。这样更方便我 debug。谢谢

**Comment by xiaoxinshiwo** [comment]
意思是提供我的blog出现bug的地址吗？https://xiaoxinshiwo.github.io/zhangyongxin/ <https://xiaoxinshiwo.github.io/zhangyongxin/>
如果是源码地址：https://github.com/xiaoxinshiwo/myblog

**Comment by Bloss** [comment]
@xiaoxinshiwo 

你可以改成下面这种格式写文章，这样可以给文章加上许多元信息，比如 tag, categories 之类。在博客的使用介绍中【文章的基础信息】一节有写，[https://wuwaki.me/yubisaki/next.html](https://wuwaki.me/yubisaki/next.html)

---
title: 书单
date: 2018-04-27 19:35:06
---

### 2018年
### 技术类
1. 大话设计模式:white_check_mark:

2. 深入理解JAVA虚拟机:white_check_mark:
3. 亿级流量网站核心技术:hourglass_flowing_sand:
4. Spring源码深度解析:hourglass_flowing_sand:
5. redis:white_check_mark:
### 小说
1. 一只特立独行的猪:hourglass_flowing_sand:
2. 黄金时代:hourglass_flowing_sand:
3. 爱你就像爱生命:hourglass_flowing_sand:
4. 第七天:white_check_mark:
> 那里树叶会向你招手，石头会向你微笑，河水会向你问候。那里没有贫贱也没有富贵，没有悲伤
也没有疼痛，没有仇也没有恨……那里人人死而平等。<br/>
> 他问："那时什么地方？"<br/>
> 我说："死无葬身之地。"<br/>

**Comment by xiaoxinshiwo** [comment]
感谢，亲测有效，但是文档缺少关键的
—
。。。
—
希望能够完善下文档


> 在 2018年11月10日，下午5:02，stickmy <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> 018年
>

**Comment by Bloss** [comment]
https://wuwaki.me/yubisaki/next.html

其实在文档中有提到，不过可能不是很醒目，谢谢建议，有时间改进一下
