### ISSUE TITLE
Can you give a example using hightlight lines in code?

### ISSUE THREAD

**Issue by farnetani** [Yubisaki/vuepress-theme-yubisaki#21]
I tried using this below, but it did not work for me.

```javascript{3-4}
let test = '';

console.log('test', test);
console.log('test hightlight');
```

**Comment by farnetani** [comment]
And taking advantage of the same issue, would I have to activate the numbers in the lines of the codes, how would I do that?

**Comment by Bloss** [comment]
https://vuepress.vuejs.org/guide/markdown.html#line-highlighting-in-code-blocks

Just like this below:

```md
```js{4}
export default {
  data () {
    return {
      msg: 'Highlighted!'
    }
  }
}
```
