### ISSUE TITLE
dev报错 Error in render: "TypeError: Cannot read property 'interval' of undefined"

### ISSUE THREAD

**Issue by Coolyang1996** [Yubisaki/vuepress-theme-yubisaki#22]
报错的版本是 "vuepress-theme-yubisaki": "^3.1.0"
另外一个项目主题版本是^3.0.2正常
![tim 20181117123825](https://user-images.githubusercontent.com/34713301/48656891-e89d0080-ea65-11e8-9046-fca6de680716.png)

**Comment by Bloss** [comment]
方便提供一个repo来复现问题吗

**Comment by Coolyang1996** [comment]
> 方便提供一个repo来复现问题吗

问题已解决,好像是以来的问题.yarn install 后就可以了.
但是还有一个问题,就是^3.0.2版本和next的3.1.0版本有什么区别吗?
因为我同样的配置,next版本的activity首页没有了.
这个是3.0.2版本的正常repo,[blog-3.0.2](https://github.com/Coolyang1996/blog)
这个是3.1.0版本的[blog-3.1.0](https://github.com/Coolyang1996/blog2)
都在master分支, npm install 然后 npm run dev 即可看到根路径下一个是首页, 一个是文章列表页.
最后一个问题是,编译后静态文件访问不到是什么原因呢?是要按照github repo名设置base吗

**Comment by Bloss** [comment]
Activity 首页是指什么呢？

具体的配置可以看官方文档 https://vuepress.vuejs.org/zh/config/

**Comment by Coolyang1996** [comment]
j

> Activity 首页是指什么呢？
> 
> 具体的配置可以看官方文档 https://vuepress.vuejs.org/zh/config/

就是# 使用自定义的 activity layout, activity: true 的这一页

**Comment by Bloss** [comment]
Sorry for break changes.

把 `activity: true` 改为 `layout: Activity`

**Comment by Bloss** [comment]
Next 版本： https://wuwaki.me/yubisaki/next.html

**Comment by PedroGao** [comment]
我现在是**3.1.0**和**3.0.2**这两个版本均有问题，配置也确实是layout: Activity,同样报这个错误

**Comment by Bloss** [comment]
> 我现在是**3.1.0**和**3.0.2**这两个版本均有问题，配置也确实是layout: Activity,同样报这个错误

方便提供复现的 repo 吗

**Comment by PedroGao** [comment]
仓库在这[https://github.com/PedroGao/september-blog](repo)
谢谢了

**Comment by Bloss** [comment]
> 仓库在这[https://github.com/PedroGao/september-blog](repo)
> 谢谢了

建议使用 ![]() 预发，这个链接通过点击是打不开的，只有手动复制链接打开

**Comment by Bloss** [comment]
@PedroGao 报的错是因为当前没有任何 type 为 post 的文章，目前的解决方案是在 docs 目录下添加一篇 post，比如 docs/blog/hello.md, 可以参考这里 [https://wuwaki.me/yubisaki/next.html#%E5%86%99%E4%B8%AA%E6%96%87%E7%AB%A0](https://wuwaki.me/yubisaki/next.html#%E5%86%99%E4%B8%AA%E6%96%87%E7%AB%A0) 中的文章基础信息.

**Comment by Bloss** [comment]
patch 在 vuepress-theme-yubisaki@3.1.3 版本中，更新即可
