### ISSUE TITLE
Try Vssue for comments

### ISSUE THREAD

**Issue by meteorlxy** [Yubisaki/vuepress-theme-yubisaki#25]
I noticed that you rewrite gitalk with Vue for comments.

[__Vssue__](https://vssue.js.org/) is based on Vue and provides a Vuepress plugin, you can integrate it easily.

Consider migrating to it? :wink:

**Comment by Bloss** [comment]
Awesome! I'ill try it later.

**Comment by Bloss** [comment]
> Vssue

Is there any way to customize the theme color?

**Comment by meteorlxy** [comment]
@Bloss 

FYI:

- https://vssue.js.org/guide/styles.html
- https://vssue.js.org/guide/vuepress.html#custom-style-variables

**Comment by Bloss** [comment]
> @Bloss
> 
> FYI:
> 
> * [vssue.js.org/guide/styles.html](https://vssue.js.org/guide/styles.html)
> * [vssue.js.org/guide/vuepress.html#custom-style-variables](https://vssue.js.org/guide/vuepress.html#custom-style-variables)

我在想使用 css3 变量是不是更加友好，无侵入式，`border-color: var(--border-color, #178df7)`

**Comment by Bloss** [comment]
我试了一下，发现有一些问题，比如 build 的时候出现 window undefined，是没兼容 ssr 吗？
发布成功后，在进入到有 vssue 组件的页面的时候，会先跳转 授权页面，但是这个 url 是 404
我使用的不是插件版本的 vssue，而是组件版本(`vssue@0.5.0`).

如果可以，能提个 PR 吗，万分感谢~

**Comment by meteorlxy** [comment]
@Bloss 

如果在 Vuepress 里单独用组件的话，需要放到 `<ClientOnly>` 里面。

如果用 `@vssue/vuepress-plugin-vssue` 的话，里面已经做了处理，就不用单独放 `<ClientOnly>` 了。

授权页面 404 是什么意思？

**Comment by meteorlxy** [comment]
我在我的主题里面通过 `@vssue/vuepress-plugin-vssue` 加上了评论，应该没什么问题，可以参考一下

https://www.meteorlxy.cn/vuepress-theme-meteorlxy/posts/2019/01/21/getting-started-zh/

https://github.com/meteorlxy/vuepress-theme-meteorlxy/blob/005f82c6d5c527aee88f85bd0ecd41c428b56da5/lib/plugins/theme/index.js#L10-L14

https://github.com/meteorlxy/vuepress-theme-meteorlxy/blob/005f82c6d5c527aee88f85bd0ecd41c428b56da5/lib/components/layouts/Post.vue#L14-L18

**Comment by Bloss** [comment]
好的，我看下

**Comment by Bloss** [comment]
404 是指这样：[https://wuwaki.me/blog/better-ts.html](https://wuwaki.me/blog/better-ts.html) 打开这链接会自动跳转到 github 的一个授权页面，但是这个页面是 404

**Comment by Bloss** [comment]
发现原因了。似乎是 repo 字段没有兼容 repo name 的方式，只兼容了 repo url

**Comment by Bloss** [comment]
获取评论似乎也有点问题：
![image](https://user-images.githubusercontent.com/9587448/51551945-908dda80-1eaa-11e9-98ec-38229245a00d.png)
![image](https://user-images.githubusercontent.com/9587448/51552006-ab604f00-1eaa-11e9-8d09-315206feb815.png)
提交评论也提交不了~
![image](https://user-images.githubusercontent.com/9587448/51552084-ccc13b00-1eaa-11e9-90af-c75c84ed6079.png)
点击提交后，似乎mei没有发起任何请求
