### ISSUE TITLE
侧边栏卡片可以加自动隐藏设置吗

### ISSUE THREAD

**Issue by boyxie** [Yubisaki/vuepress-theme-yubisaki#26]
笔记上看现在的GitHub卡片占位有点多，如果能隐藏，主内容宽度是否可以自适应，如果有可以设置的地方，帮忙回复一下哈

**Comment by Bloss** [comment]
> 笔记上看现在的GitHub卡片占位有点多，如果能隐藏，主内容宽度是否可以自适应，如果有可以设置的地方，帮忙回复一下哈

目前是通过 media query 来决定 card 卡片是放在侧边还是放在底部的。分界线是 960px，低于这个值的文章是全屏展示的
