### ISSUE TITLE
Failed to load custom theme "yubisaki". File vuepress-theme-yubisaki/Layout.vue does not exist

### ISSUE THREAD

**Issue by chavesgu** [Yubisaki/vuepress-theme-yubisaki#28]

**Comment by Bloss** [comment]
The version of vuepress should be 1.x.
Try to run `npm install vuepress@next` in project

**Comment by chavesgu** [comment]
> The version of vuepress should be 1.x.
> Try to run `npm install vuepress@next` in project, also install globally: `npm i vuepress@next -g`.
> You can use the [vuepress-theme-yubisaki-example](https://github.com/bloss/vuepress-theme-yubisaki-example) as a base.

thanks, but vuepress@1.0+ is beta?

**Comment by Bloss** [comment]
> > The version of vuepress should be 1.x.
> > Try to run `npm install vuepress@next` in project, also install globally: `npm i vuepress@next -g`.
> > You can use the [vuepress-theme-yubisaki-example](https://github.com/bloss/vuepress-theme-yubisaki-example) as a base.
> 
> thanks, but vuepress@1.0+ is beta?

No, 1.0+ has been maintained for a long time. Documentation: [https://v1.vuepress.vuejs.org/](https://v1.vuepress.vuejs.org/)
