### ISSUE TITLE
vue error

### ISSUE THREAD

**Issue by chavesgu** [Yubisaki/vuepress-theme-yubisaki#29]
i use your config, but

[Vue warn]: Error in render: "TypeError: Cannot read property 'interval' of undefined"

found in

---> <Layout> at node_modules/vuepress-theme-yubisaki/layouts/Layout.vue
       <GlobalLayout> at node_modules/@vuepress/core/lib/app/components/GlobalLayout.vue
         <Root>

**Comment by Bloss** [comment]
Any repo to reproduce?

**Comment by chavesgu** [comment]
> Any repo to reproduce?

i resolve this,  because i don't set "type: post"  at start, so throw err above

**Comment by Bloss** [comment]
> > Any repo to reproduce?
> 
> i resolve this, because i don't set "type: post" at start, so throw err above

Got it. I will create a patch to handle compatibility issues.
