### ISSUE TITLE
I want to install old theme for my project

### ISSUE THREAD

**Issue by Overcase** [Yubisaki/vuepress-theme-yubisaki#30]
install new theme and vuepress@next  old config  file runing but content boom . I want to install old theme. that is x.x.x?

**Comment by Bloss** [comment]
Try this

```
"vuepress": "^0.14.4",
"vuepress-theme-yubisaki": "^3.0.3"
```

**Comment by Overcase** [comment]
can you paster out your blog directory tree？ I look your theme@next articles in the blog  update my blog configuration but content is white. Tag is normal . Home undefined blog articles.

**Comment by Overcase** [comment]
"devDependencies": {
    "vuepress-theme-yubisaki": "^3.1.4"
  },
  "dependencies": {
    "markdown-it-imsize": "^2.0.1",
    "markdown-it-task-lists": "^2.1.1",
    "vuepress": "^1.0.0-alpha.39"
  }
