### ISSUE TITLE
can you give me your blog configuration?

### ISSUE THREAD

**Issue by Overcase** [Yubisaki/vuepress-theme-yubisaki#31]
can you paster out your blog directory tree？ I look your theme@next articles in the blog update my blog configuration but content is white. Tag is normal . Home undefined blog articles.

**Comment by Overcase** [comment]
this is my dependencies

```
"devDependencies": {
    "vuepress-theme-yubisaki": "^3.1.4"
  },
  "dependencies": {
    "markdown-it-imsize": "^2.0.1",
    "markdown-it-task-lists": "^2.1.1",
    "vuepress": "^1.0.0-alpha.39"
  }
```

**Comment by Bloss** [comment]
You can use [https://github.com/Bloss/vuepress-theme-yubisaki-example](https://github.com/Bloss/vuepress-theme-yubisaki-example) as a base.
